spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: secret
      database: iptstud
      port: 27017
#
#security:
#  oauth2:
#    resource:
#      filter-order: 3


server:
  context-path: /uaa
  port: 5000