security:
#  oauth2:
#    resource:
#      filter-order: 3
    client:
      clientId: bookcase-service
      clientSecret: secret
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: bookcase-mongodb
      username: user
      password: secret
      database: iptstud
      port: 27017

server:
  context-path: /bookcase
  port: 6000